"""initial migration with bio

Revision ID: ba7f56ac61f3
Revises: 5718b37f3308
Create Date: 2025-04-09 13:46:17.377481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7f56ac61f3'
down_revision = '5718b37f3308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallpaper', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wallpaper')

    # ### end Alembic commands ###
